/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import encode.Coding;
import helper.Encode;
import helper.Files;
import helper.Path;
import java.io.UnsupportedEncodingException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yaroslav
 */
public class EncodeForm extends javax.swing.JFrame {

    private int prevSelected = 0;

    /**
     * Creates new form EncodeForm
     */
    public EncodeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel1.setText("Исходный текст");

        jLabel2.setText("Ключ");

        jLabel3.setText("Закодированный текст");

        jButton1.setText("Обзор");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Путь к исходному тексту");

        jButton2.setText("Обзор");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Путь к ключу");

        jLabel6.setText("Подключ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Циклический");
        jRadioButton1.setActionCommand("0");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Скремблер");
        jRadioButton2.setActionCommand("1");

        jLabel7.setText("Функция");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Единичная");
        jRadioButton3.setActionCommand("0");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("XOR");
        jRadioButton4.setActionCommand("1");

        jLabel8.setText("Кодировка");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Символьная", "Двоичная", "Шестнадцатеричная" }));

        jButton3.setText("Кодировать");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Сгенерировать ключ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(4, 4, null, 1));

        jLabel9.setText("Длина ключа");

        jButton5.setText("Сохранить");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Кол-во раундов");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(2, 2, 16, 1));

        jButton6.setText("Отобразить");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jLabel6)
                                    .addComponent(jRadioButton2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jLabel7)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1))
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(91, 91, 91)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel10)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = Files.getAbsolutePath();
        jTextField1.setText(path);
        jTextArea1.setText(Files.readFile(path));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = Files.getAbsolutePath();
        jTextField2.setText(path);
        jTextArea2.setText(Files.readFile(path));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int size = (Integer) jSpinner1.getValue();
        Files.saveToFile(Path.PATH_TO_KEY, keyGeneration(size));
        jTextField2.setText(Path.PATH_TO_KEY);
        jTextArea2.setText(Files.readFile(Path.PATH_TO_KEY));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int numberRounds = (Integer) jSpinner2.getValue();
            String text = "", key = "";
            int tupeFunc = Integer.parseInt(buttonGroup2.getSelection().getActionCommand());
            int tupeKey = Integer.parseInt(buttonGroup1.getSelection().getActionCommand());
            switch (jComboBox1.getSelectedIndex()) {
                case 0:
                    text = jTextArea1.getText();
                    key = jTextArea2.getText();
                    break;
                case 1:
                    text = Encode.binToString(jTextArea1.getText(), 8);
                    key = Encode.binToString(jTextArea2.getText(), 8);
                    break;
                case 2:
                    text = Encode.hexToString(jTextArea1.getText());
                    key = Encode.hexToString(jTextArea2.getText());
                    break;
            }
            Coding coding = new Coding();
            String encodedtext = coding.getEncodedText(text, key, numberRounds, tupeFunc, tupeKey);
            jTextArea3.setText(Encode.binToString(encodedtext, 8));
            Files.saveToFile(Path.PATH_TO_ENCODE_FILE, Encode.binToString(encodedtext, 8));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                if (prevSelected == 1) {
                    jTextArea1.setText(Encode.binToString(jTextArea1.getText(), 8));
                    jTextArea2.setText(Encode.binToString(jTextArea2.getText(), 8));
                    jTextArea3.setText(Encode.binToString(jTextArea3.getText(), 8));
                } else if (prevSelected == 2) {
                    try {
                        jTextArea1.setText(Encode.hexToString(jTextArea1.getText()));
                        jTextArea2.setText(Encode.hexToString(jTextArea2.getText()));
                        jTextArea3.setText(Encode.hexToString(jTextArea3.getText()));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                prevSelected = 0;
                break;
            case 1:
                if (prevSelected == 0) {
                    jTextArea1.setText(Encode.stringToBin(jTextArea1.getText(), 8));
                    jTextArea2.setText(Encode.stringToBin(jTextArea2.getText(), 8));
                    jTextArea3.setText(Encode.stringToBin(jTextArea3.getText(), 8));
                } else if (prevSelected == 2) {
                    try {
                        jTextArea1.setText(Encode.stringToBin(Encode.hexToString(jTextArea1.getText()), 8));
                        jTextArea2.setText(Encode.stringToBin(Encode.hexToString(jTextArea2.getText()), 8));
                        jTextArea3.setText(Encode.stringToBin(Encode.hexToString(jTextArea3.getText()), 8));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                prevSelected = 1;
                break;
            case 2:
                if (prevSelected == 0) {
                    try {
                        jTextArea1.setText(Encode.stringToHex(jTextArea1.getText()));
                        jTextArea2.setText(Encode.stringToHex(jTextArea2.getText()));
                        jTextArea3.setText(Encode.stringToHex(jTextArea3.getText()));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (prevSelected == 1) {
                    try {
                        jTextArea1.setText(Encode.stringToHex(Encode.binToString(jTextArea1.getText(), 8)));
                        jTextArea2.setText(Encode.stringToHex(Encode.binToString(jTextArea2.getText(), 8)));
                        jTextArea3.setText(Encode.stringToHex(Encode.binToString(jTextArea3.getText(), 8)));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                prevSelected = 2;
                break;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                if (prevSelected == 1) {
                    Files.saveToFile(jTextField1.getText(), Encode.binToString(jTextArea1.getText(), 8));
                    Files.saveToFile(jTextField2.getText(), Encode.binToString(jTextArea2.getText(), 8));
                    Files.saveToFile(Path.PATH_TO_ENCODE_FILE, Encode.binToString(jTextArea3.getText(), 8));
                } else if (prevSelected == 2) {
                    try {
                        Files.saveToFile(jTextField1.getText(),Encode.hexToString(jTextArea1.getText()));
                        Files.saveToFile(jTextField2.getText(),Encode.hexToString(jTextArea2.getText()));
                        Files.saveToFile(Path.PATH_TO_ENCODE_FILE,Encode.hexToString(jTextArea3.getText()));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            case 1:
                if (prevSelected == 0) {
                    Files.saveToFile(jTextField1.getText(),Encode.stringToBin(jTextArea1.getText(), 8));
                    Files.saveToFile(jTextField2.getText(),Encode.stringToBin(jTextArea2.getText(), 8));
                    Files.saveToFile(Path.PATH_TO_ENCODE_FILE,Encode.stringToBin(jTextArea3.getText(), 8));
                } else if (prevSelected == 2) {
                    try {
                        Files.saveToFile(jTextField1.getText(),Encode.stringToBin(Encode.hexToString(jTextArea1.getText()), 8));
                        Files.saveToFile(jTextField2.getText(),Encode.stringToBin(Encode.hexToString(jTextArea2.getText()), 8));
                        Files.saveToFile(Path.PATH_TO_ENCODE_FILE,Encode.stringToBin(Encode.hexToString(jTextArea3.getText()), 8));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            case 2:
                if (prevSelected == 0) {
                    try {
                        Files.saveToFile(jTextField1.getText(),Encode.stringToHex(jTextArea1.getText()));
                        Files.saveToFile(jTextField2.getText(),Encode.stringToHex(jTextArea2.getText()));
                        Files.saveToFile(Path.PATH_TO_ENCODE_FILE,Encode.stringToHex(jTextArea3.getText()));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (prevSelected == 1) {
                    try {
                        Files.saveToFile(jTextField1.getText(),Encode.stringToHex(Encode.binToString(jTextArea1.getText(), 8)));
                        Files.saveToFile(jTextField2.getText(),Encode.stringToHex(Encode.binToString(jTextArea2.getText(), 8)));
                        Files.saveToFile(Path.PATH_TO_ENCODE_FILE,Encode.stringToHex(Encode.binToString(jTextArea3.getText(), 8)));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(EncodeForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private String keyGeneration(int size) {
        char[] chars = "abcdefghijklmnopqrstuvwxyz1234567890() .,".toCharArray();
        StringBuilder sb = new StringBuilder(size);
        Random random = new Random();
        for (int i = 0; i < size; i++) {
            char c = chars[random.nextInt(chars.length)];
            sb.append(c);
        }
        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncodeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncodeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncodeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncodeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncodeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
